-- Promotion Management System Database Schema
-- Database: promotion_db
-- Created for: Promotion Management System Project

-- Create Database
CREATE DATABASE IF NOT EXISTS promotion_db;
USE promotion_db;

-- Drop tables if they exist (for clean setup)
DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS users;

-- Create users table
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create promotions table
CREATE TABLE promotions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    banner_image_path VARCHAR(500),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_start_date (start_date),
    INDEX idx_end_date (end_date),
    INDEX idx_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default admin user
-- Password: admin123 (BCrypt hashed - generated by Spring Security)
-- Note: If you prefer, you can skip these INSERT statements and let DataInitializer.java create the users
INSERT INTO users (username, password, email, role, is_active) VALUES
('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iwy7p8fO', 'admin@promotionsystem.com', 'ADMIN', TRUE)
ON DUPLICATE KEY UPDATE username=username;

-- Insert default regular user
-- Password: user123 (BCrypt hashed - generated by Spring Security)
INSERT INTO users (username, password, email, role, is_active) VALUES
('user', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iwy7p8fO', 'user@promotionsystem.com', 'USER', TRUE)
ON DUPLICATE KEY UPDATE username=username;

-- Note: The passwords above are BCrypt hashed versions of:
-- admin: admin123
-- user: user123
-- These hashes are compatible with Spring Security's BCryptPasswordEncoder
-- 
-- Alternative: If you skip the INSERT statements above, the DataInitializer.java
-- component will automatically create these users when the Spring Boot application starts

-- Verify the setup
SELECT 'Database setup completed successfully!' AS status;
SELECT COUNT(*) AS user_count FROM users;
SELECT COUNT(*) AS promotion_count FROM promotions;

